name: orpheus_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # База данных
  sqflite: ^2.3.0
  path: ^1.8.3

  # Криптография и безопасность
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.0.0

  # Утилиты
  provider: ^6.1.1
  rxdart: ^0.27.7
  intl: ^0.18.0
  permission_handler: ^11.0.1

  # Сеть
  web_socket_channel: ^2.4.0

  # UI и Медиа
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  audioplayers: ^5.2.1
  qr_flutter: ^4.1.0

  # Звонки
  flutter_webrtc: ^1.2.0

  # Firebase (Уведомления) - ДОБАВЛЕНО
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9

  # Авторизация и биометрия
  local_auth: ^2.1.6
  share_plus: ^12.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/


# --- НАСТРОЙКА ИКОНКИ ПРИЛОЖЕНИЯ ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png" # <-- Твой файл
  min_sdk_android: 21
  # remove_alpha_ios: true # Раскомментируй, если иконка прозрачная (для iOS важно)

# --- НАСТРОЙКА ЗАСТАВКИ (SPLASH SCREEN) ---
flutter_native_splash:
  color: "#000000" # Черный фон
  image: "assets/images/logo.png" # Логотип по центру

  # Специально для Android 12+ (там новая система сплешей)
  android_12:
    color: "#000000"
    image: "assets/images/logo.png"
    icon_background_color: "#000000"

  # На весь экран или нет (false = убрать статус бар)
  fullscreen: true